# -*- coding: utf-8 -*-
"""Visualização-streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yllb_4coZESLbnv7eBxXYnlhAJIuirlO
"""

pip install streamlit

import pandas as pd #Criar dataframe
import numpy as np
import matplotlib.pyplot as plt # Criar gráficos
import seaborn as sns
import streamlit as st

path='/content/sample_data/machinery_data.csv'
df=pd.read_csv(path)

df.info()
df.head()

#Filtrar por máquina e somar as falhas

#lucrodo=df[(df['runtime']<=i)&(df['runtime']>(i-30))]['profit']
x=df['Machine_Type'].unique()
y=df.groupby('Machine_Type')['Failures'].sum()


print(x)
print(y)

"""#Título do dashboard"""

st.title('Dashboard de Produção de Máquinas')

plt.plot(x,y)



plt.show() #Exibir Gráfico